language: Node
services:
  - docker
​
# Pre-testing installs
install:
  - echo "nothing needs to be installed"
​
# Scripts to be run such as tests
before_script:
  - echo "no tests"
​
script:
  - docker --version # print the version for logging
  # Build images
  - docker-compose -f docker-compose-build.yaml build --parallel
  
  # Tag images
  - docker tag reverseproxy  ndaruga/reverseproxy:v4
  - docker tag udagram-api-feed  ndaruga/udagram-api-feed:v4
  - docker tag udagram-api-user  ndaruga/udagram-api-user:v4
  - docker tag udagram-frontend  ndaruga/udagram-frontend:v4
​
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push  ndaruga/reverseproxy:v4
  - docker push  ndaruga/udagram-api-feed:v4
  - docker push  ndaruga/udagram-api-user:v4
  - docker push  ndaruga/udagram-frontend:v4